services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: Geniapp
      POSTGRES_USER: geniapp_admin
      POSTGRES_PASSWORD: LQtq38Gdnr3Q
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: PostgreSQL
  
  message_queue:
    image: rabbitmq
    restart: always
  
  master:
    image: geniapp.master
    restart: always
    depends_on: 
      database:
        condition: service_started
      message_queue:
        condition: service_started
    build:
      context: .
      dockerfile: ../Geniapp.Master/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "Production"
      ConnectionStrings__Master: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"
      ConnectionStrings__Shard: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"
      MessageQueue__HostName: "message_queue"
      Work__DelayInSeconds: 1
      Tenants__Count: 6
  
  worker:
    image: geniapp.worker
    restart: always
    depends_on:
      master:
        condition: service_started
    build:
      context: .
      dockerfile: ../Geniapp.Worker/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "Production"
      ConnectionStrings__Master: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"
      ConnectionStrings__Shard: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"
      MessageQueue__HostName: "message_queue"
      Work__MinWorkDurationInSeconds: 0.3
      Work__MaxWorkDurationInSeconds: 0.9
  
  frontend:
    image: geniapp.frontend
    restart: always
    depends_on:
      master:
        condition: service_started
    build:
      context: .
      dockerfile: ../Geniapp.Frontend/Dockerfile
    ports:
      - 80:8080
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Master: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"
      ConnectionStrings__Shard: "Server=database;Port=5432;Database=Geniapp;User Id=geniapp_admin;Password=LQtq38Gdnr3Q;"